package main.java.com.pixolestudios.skinUtils;

public enum WeaponCollection {

    // DATA FROM https://csgoitems.pro/en/collections/all

    PRISMA,
    DANGER_ZONE,
    BLACKSITE,
    INFERNO_2018,
    NUKE_2018,
    HORIZON,
    CLUTCH,
    SPECTRUM_2,
    OPERATION_HYDRA,
    SPECTRUM,
    GLOVE,
    GAMMA_2,
    GAMMA,
    CHROMA_3,
    WILDRIRE,
    REVOLVER,
    SHADOW,
    FALCHION,
    GODS_AND_MONSTERS,
    CHOP_SHOP,
    RISING_SUN,
    CHROMA_2,
    CHROMA,
    VANGUARD,
    CACHE,
    eSPORTS_2014_SUMMER,
    OVERPASS,
    COBBLESTONE,
    BAGGAGE,
    BREAKOUT,
    HUNSTMAN,
    BANK,
    HUNTSMAN_OLD,
    PHOENIX,
    eSPORTS_WINTER,
    ARMS_DEAL_3,
    WINTER_OFFENSIVE,
    TRAIN,
    DUST_2,
    MIRAGE,
    LAKE,
    ITALY,
    SAFEHOUSE,
    BRAVO,
    ARMS_DEAL_2,
    ALPHA,
    AZTEC,
    DUST,
    VERTIGO,
    MILITIA,
    INFERNO,
    NUKE,
    OFFICE,
    eSPORTS_2013,
    ASSAULT,
    ARMS_DEAL;
}
